version: 0.2

env:
  secrets-manager:
    GITHUB_TOKEN: github-packages-token:GITHUB_TOKEN

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo "Configuring Maven for GitHub Packages"
      - mkdir -p ~/.m2
      - |
        cat <<EOF > ~/.m2/settings.xml
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
          <servers>
            <server>
              <id>github</id>
              <username>virinchisrao</username>
              <password>${GITHUB_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging artifacts...
      - mvn package

artifacts:
  files:
    - target/*.war
  discard-paths: no
